# Site settings
title: Ganapati Press
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Publishing the Works of Sri Chinmoy
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ganapatipress.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

permalink: /:title.html

gems:
  - jekyll-feed
  - jekyll-sitemap
